### ISSUE TITLE
How to make on windows?

### ISSUE THREAD

**Issue by JayCroghan** [gta5-map/Social-Club-API-cheat-sheet#14]
I found a sphinx make.cmd but it doesn't work and I'm not interested in spending a lot of time trying to set this up before I even start playing with it.

How can I make on windows?

Thanks

**Comment by JayCroghan** [comment]
Is that a tumbleweed?

**Comment by frdmn** [comment]
Nope it's not. Just missed your issue. 

Nothing different as any other operating system. Install the requirements/dependencies and run:

```
sphinx-build -b html -d _build/doctrees docs _build/html
```
