### ISSUE TITLE
Crew hierarchy endpoint not working

### ISSUE THREAD

**Issue by r3m4k3** [gta5-map/Social-Club-API-cheat-sheet#2]
Hi there,

I have provlem with getting data about my crew.
I have such curl command: 

 curl -v -XGET -H "Content-type: application/json" 'http://pl.socialclub.rockstargames.com/crewapi/[CREW_NAME]/hierarchy/10/false?_=141977749113' -L --insecure

Curl is still trying to connect to the IP address (trying 192.81.241.19) and then I got connection timed out error.

In my browser link http://pl.socialclub.rockstargames.com/crewapi/[CREW_NAME]/hierarchy/10/false?_=141977749113 is working correctly, it returns me asked data.

Why is that?
Has something changed in the API structure?

Thanks, best regards

**Comment by frdmn** [comment]
Rockstar implemented a bunch of mean HTTP header checks to avoid requests sent by non-browsers like cURL. You need to sent _exactly_ the same headers as your browser does, see this comment: https://github.com/gta5-map/Social-Club-API-cheat-sheet/issues/1#issuecomment-153733540
