### ISSUE TITLE
Can't get __RequestVerificationToken

### ISSUE THREAD

**Issue by r3m4k3** [gta5-map/Social-Club-API-cheat-sheet#3]
Hi there,

I'm trying to get __RequestVerificationToken property from http://socialclub.rockstargames.com/.
But it doesn't work.
Have they sth changed in this part of API?

Best regards

**Comment by LordTiggy** [comment]
Check #1; all the info is in there

**Comment by r3m4k3** [comment]
Thanks for the answer!
I saw that. But I don't think these issues are connected with each other.
I'm using correct headers, user agent etc. My ip address wasn't blocked by
Rockstar Games. Later I will describe it more precisely.

**Comment by LordTiggy** [comment]
Something has changed on Rockstar's side; did you try with the new headers provided in #1

Some seem to be ale to connect so it should work with those headers.

//EDIT
Nevermind ... just saw you are the one who posted the headers :)

**Comment by frdmn** [comment]
@r3m4k3 Can you elaborate "But it doesn't work"? What exactly? Can you still see it in the page source but cant extract it?

**Comment by r3m4k3** [comment]
@frdmn Yes, exactly the same.
The code based on your parser with additional headers from issue #1 .

```
$defaultHeaders = array(
  'Pragma: no-cache',
  'Accept-Encoding: gzip, deflate, sdch',
  'Accept-Language: en-US,en;q=0.8,en-US;q=0.6,en;q=0.4',
  'Upgrade-Insecure-Requests: 1',
  'User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36',
  'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'Cache-Control: no-cache',
  'Connection: keep-alive'
);

$ch = curl_init();
curl_setopt($ch, CURLOPT_COOKIEJAR, "cookie_jar.txt");
curl_setopt($ch, CURLOPT_URL,"http://socialclub.rockstargames.com/");
curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_VERBOSE, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $defaultHeaders);
$buffer = curl_exec($ch);
curl_close($ch);
unset($ch);

$parsed_rvt = str_get_html($buffer)->find('input[name=__RequestVerificationToken]', 0)->value;
```

It returns null.
Buffer is hardcoded string of some kind of "Chinese": ‹í½`I–%&/mÊ{JõJ×àt¡€`$Ø@ìÁˆÍæ’ìiG#)«*Êe etc.
Of course I have included Simple Html Dom library.

**Comment by frdmn** [comment]
@r3m4k3 Aaaah, thats easy to fix: The buffer that you see there is not in chinese actually, it's just plain gzip encoded. 😬

Add the following header to your `CURLOPT`s and it should do the trick:

``` php
curl_setopt($ch, CURLOPT_ENCODING , "");
```

**Comment by r3m4k3** [comment]
@frdmn That's right.
Dank je wel! :)

**Comment by r3m4k3** [comment]
@frdmn 
Huh, but I've got still problem with signing in.
I can see sign in page as a result, but I'm not logged in.

$ch = curl_init();
curl_setopt($ch, CURLOPT_COOKIEJAR, "cookie_jar.txt");
curl_setopt($ch, CURLOPT_COOKIEFILE, "cookie_jar.txt");
curl_setopt($ch, CURLOPT_URL,"https://socialclub.rockstargames.com/profile/signin");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "login=".$username."&password=".$password."&__RequestVerificationToken=".$parsed_rvt);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36',
    'Content-Type: application/x-www-form-urlencoded'
  )
);

What am I doing wrong this time?
Thanks :)

// I know that this is not connected with topic of this issue.
// But I don't want to create a new one.

**Comment by frdmn** [comment]
@r3m4k3 What's your response when you fire that request like that?

**Comment by r3m4k3** [comment]
@frdmn Sign in page 
![screenshot from 2015-11-19 15 24 32](https://cloud.githubusercontent.com/assets/8336855/11273100/cd90367e-8ed1-11e5-8e2c-cbaa5db8e625.png)

**Comment by r3m4k3** [comment]
@frdmn Any idea? Can you sign in via curl?

**Comment by thecrossandcrown** [comment]
Has there been any progress on this?

**Comment by frdmn** [comment]
@r3m4k3 The problem in this case is that SC wants us to solve the ReCaptcha (which you probably don't see in your screenshot because its post-loaded via JavaScript). The only way to work around this is to open the login page of SC in a "usual" browser and sign in manually so the ReCaptcha shows up there instead. Once you've solved that, you should be also able to login using the example parser.

@thecrossandcrown I won't give up that easily though. I plan to rewrite this in JavaScript and try to make use of [PhantomJS](http://phantomjs.org/) to simulate a full browser engine at some point. That way I can hopefully proxy the possible captchas to the user's screen, so they can solve and input the result manually. 

Still, I'm afraid a fully automatic and especially permanent solution without user interaction is impossible at the moment unless R\* gives us some proper API's to work with :(
