### ISSUE TITLE
Test each endpoints

### ISSUE THREAD

**Issue by frdmn** [gta5-map/Social-Club-API-cheat-sheet#4]
It's been a while since I've worked with this, so it's time to go through each of the API endpoints and see if they still work like documented in the cheat sheet.

**Comment by frdmn** [comment]
Since I don't have that much spare time lately, I would appreciate any help :)

**Comment by LordTiggy** [comment]
Checking if the examples you gave are still working is that it? If that's it, I might try some out for you :)

Just let me know what I should test; I am no coder but I can check things lol

**Comment by frdmn** [comment]
@LordTiggy exactly! I mean, it's quite a long time ago since I created this cheat sheet - Odds are that the Rockstar backend changed over the time and some of the "cheat sheet" parts don't even work properly anymore, because we might need additional parameters to send, etc. 

Just want to make sure that this project is still up to date - and if there are wrong information, that we collect them and fix at some point of course :)

**Comment by khubbaib** [comment]
Hi i tried the [link](http://socialclub.rockstargames.com/crew/shine_thugz/hierarchy/1000/false?_=1419777491133) given in cheat sheat but this link gives me empty respsone.. i am freelancer and i have a project to show the members and list all other member in hierarchy...

Can any one here to help me?

**Comment by frdmn** [comment]
@khubbaib This is because you just "click" the given link. It's an internal API endpoint that you can only use if you send the proper authorization cookies. You can find an example parser written in PHP in the https://github.com/gta5-map/Social-Club-example-parser repository. 

More information about authentication in this cheat sheet: https://github.com/gta5-map/Social-Club-API-cheat-sheet#22-authentication

**Comment by frdmn** [comment]
Bump

**Comment by frdmn** [comment]
Tested all the currently listed endpoints \o/
